db backup structured

diff --git a/.github/workflows/db-backup.yml b/.github/workflows/db-backup.yml
--- a/.github/workflows/db-backup.yml
+++ b/.github/workflows/db-backup.yml
@@ -27,15 +27,15 @@ jobs:
           TIMESTAMP=$(date +"%Y%m%d%H%M")
           BACKUP_DIR="$HOME/pg_snapshots"
           BACKUP_FILE="${BACKUP_DIR}/postgres_backup_${TIMESTAMP}.sql"
-          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
           STORE_NUMBER_OF_DAYS_BACKUP=${STORE_NUMBER_OF_DAYS_BACKUP:-7}
 
           mkdir -p $BACKUP_DIR
+          docker exec -t ${{ env.POSTGRES_CONTAINER }} pg_dumpall -U ${{ secrets.POSTGRES_USER }} > "$BACKUP_FILE"
 
-          if ! docker exec -t ${{ env.POSTGRES_CONTAINER }} pg_dumpall -U "$POSTGRES_USER" > "$BACKUP_FILE"; then
-            echo "Database backup failed. Please check the logs for more information."
-            exit 1
-          fi
+          # if ! docker exec -t ${{ env.POSTGRES_CONTAINER }} pg_dumpall -U ${{ secrets.POSTGRES_USER }} > "$BACKUP_FILE"; then
+          #   echo "Database backup failed. Please check the logs for more information."
+          #   exit 1
+          # fi
 
           find $BACKUP_DIR -type f -name "*.sql" -mtime "+$STORE_NUMBER_OF_DAYS_BACKUP" -delete
           echo "Backup completed at $TIMESTAMP"
